## Site metadata ##

title: Jekyll Actions Guide
description: How to setup GH Pages + GH Actions for use with Jekyll 4

### Built settings ###

url: "https://akatief.github.io"
baseurl: "/jekylltest"

github_username: MichaelCurrin

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
  
remote_theme: mmistakes/minimal-mistakes
