## Site metadata ##

title: Quantumist
description: How to setup GH Pages + GH Actions for use with Jekyll 4
name: "Federico Tiblias"

author: Federico Tiblias
### Built settings ###

url: "https://akatief.github.io"
baseurl: ""

github_username: akatief

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-archives
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-scholar

relative_links:
  enabled: true
  collections: true

markdown: kramdown

jekyll-archives:
  enabled: all # []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air" # "quantum", "air", "aqua", "default", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
